### ISSUE TITLE
Active or Abandoned?

### ISSUE THREAD

**Issue by nevsie** [verbb/tablemaker#25]
While I am seeing no major issues with this field and its functionality...
No updates in over 4 years has me worried about using it.

Is it being maintained (if needed)?
Will it be converted and suitable for Craft 4 use?

Thanks, Neil

**Comment by samstevens** [comment]
I would support this being a paid plugin if it ensures continued support and an upgrade path for Craft 4.

+1

**Comment by jamesmacwhite** [comment]
I've had a fork this plugin under Craft 3 due to the lack of Craft 2 -> 3 migration track along with multiline support on certain fields (used in Craft 2). There hasn't been a major update since the Craft 3 port of it, so I'd share similar concerns, especially for Craft 4 support.

I would equally support it being a paid plugin too, I'd have to class this plugin abandoned at the moment though, due to lack of updates and no response from issues/PRs in years.

**Comment by angieherrera** [comment]
Wondering about this too, especially as Craft 4 is not far off!

**Comment by danbrellis** [comment]
I also have a [fork of this plugin](https://github.com/danbrellis/tablemaker) which lets me use any fields a normal table supports (dropdown, multiline, color, email, etc). Not a PR because I haven't thorough testing (only using it on my site). Maybe someone can reach out to them and offer to take it over? Would also support it as paid plugin.

**Comment by engram-design** [comment]
We've recently acquired this from the Supercool team. Read our [blog post](https://verbb.io/blog/supercool-plugins-have-a-new-home) for more details.

I'll take a look at your fork @danbrellis and there's also one pending for https://github.com/verbb/tablemaker/pull/26 once I have we have a change to cleanup things

**Comment by danbrellis** [comment]
@engram-design this is awesome news. I'll try and submit a PR if it'll make it easier for you to review. Glad to hear this plugin can get some new life!

**Comment by engram-design** [comment]
@danbrellis No stress if you can't, as I'll likely be doing a full audit for Craft 3 first, then upgrading to Craft 4, so there might be a bunch of stuff changed. But don't let that stop you!

**Comment by angieherrera** [comment]
Super stoked!

**Comment by jamesmacwhite** [comment]
@engram-design Happy to PR some Craft 3 stuff on my fork if required.

Main thing for me was migration handling between Craft 2 to 3

https://github.com/nottinghamcollege/tablemaker/blob/master/src/migrations/m190412_182837_update_craft2_fieldtype.php

There is also a weird scenario where somehow the fieldtype settings got written as plugin settings in Craft 2, I saw this on a Craft 2 project which has a settings key defined on the plugin, even though it doesn't have any settings

https://github.com/nottinghamcollege/tablemaker/blob/master/src/migrations/m220602_070853_remove_plugin_settings.php

**Comment by engram-design** [comment]
Closing in favour of https://github.com/verbb/tablemaker/issues/27, this is no longer abandoned!
